develop init
plusik10/antibruteforceservice pull request #1
Opened 2023-10-07 07:49 UTC by plusik10

2023-10-10 19:14 UTC, isteshkov requested changes

2023-10-10 19:14 UTC, isteshkov commented on pkg/postgres/postgres.go
> +	_defaultMaxPoolSize  = 1
я бы еще вынес этот параметр в енвы

2023-10-10 19:14 UTC, isteshkov commented on internal/controller/http/v1/router.go
> +func toWhiteList(ctx context.Context, netManager usecase.NetListManager) http.HandlerFunc {
завязывать юзкейс на http метод - плохая практика, абстрагируемся от всего этого, у нас потом grpc ручки будут, например

2023-10-10 19:14 UTC, isteshkov commented on internal/controller/http/v1/router.go
> +			request.Text = err.Error()
если в этом поле ты планируешь возвращать ошибку, то назови его так, что бы клиент понимал чего ожидать от этого поля

2023-10-10 19:14 UTC, isteshkov commented on internal/controller/http/v1/router.go
> +		json.NewEncoder(w).Encode(request)
еще нам нужны коды ответов HTTP (400, 500, 200...), это надо определять исходя из бизнес требований (ТЗ), если есть какая то валидация - это к 400 ошибке, если отваливается инфра (например БД) - 500

2023-10-10 19:14 UTC, isteshkov commented on internal/controller/http/v1/router.go
> +func toWhiteList(ctx context.Context, netManager usecase.NetListManager) http.HandlerFunc {
то есть на каждый юзкейс свой метод, в котором есть определенный интерфейсом вход и выход, обработки транспорта (http, rpc) задача другого слоя

2023-10-11 07:39 UTC, plusik10 commented on pkg/postgres/postgres.go
> +	_defaultMaxPoolSize  = 1
Он уже в env, PG_POOL_MAX

2023-10-23 10:51 UTC, merged